### ISSUE TITLE
Import Issues with Cython Module

### ISSUE THREAD

**Issue by tylerjereddy** [tylerjereddy/hausdorff_scipy#1]
At the moment attempting to run `nosetests test_hausdorff.py` (at path: `scipy/spatial/tests`) produces the traceback shown below. This is probably related to my recent switch to Cython from the original python module.

```
======================================================================
ERROR: Failure: ImportError (No module named hausdorff)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/treddy/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/treddy/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/treddy/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/treddy/github_projects/scipy/scipy/spatial/tests/test_hausdorff.py", line 5, in <module>
    import scipy.spatial.hausdorff
ImportError: No module named hausdorff
```

**Comment by tylerjereddy** [comment]
This was simply the result of an interfering scipy version on my machine -- so closing!
